specVersion: 0.2.0
name: moonbeam-alpha-subql-starter
version: 0.0.4
description: This project can be use as a starting point for moonbeam alpha network.
repository: https://github.com/subquery/moonbeam-alpha-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
